In [12]:
import numpy as np

In [13]:
x=np.array([[1,1,1,1,1,1,1,1,1,1], [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]])  # Here I am taking Extra column having value 1 because we can use direct formula
y = np.array([7.3, 9.1, 10.8, 13.0, 15.2, 16.8, 19.1, 20.7, 23.2, 25.5])

In [14]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [15]:
w_updated,w_ini = np.zeros((2,1)) , np.zeros((2,1))

for i in range(1000):
    print(w_ini)
    w_updated = w_ini - (0.001 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated
    


[[0.]
 [0.]]
[[0.10713333]
 [0.69986667]]
[[0.18789067]
 [1.21617267]]
[[0.2491784 ]
 [1.59699902]]
[[0.29609391]
 [1.87783273]]
[[0.33239942]
 [2.08486556]]
[[0.36087168]
 [2.23742875]]
[[0.38356015]
 [2.34979008]]
[[0.40197745]
 [2.43248008]]
[[0.41724   ]
 [2.49327102]]
[[0.43017179]
 [2.53789933]]
[[0.441381  ]
 [2.57059887]]
[[0.45131651]
 [2.59449452]]
[[0.4603096 ]
 [2.61189266]]
[[0.4686048 ]
 [2.62449552]]
[[0.4763826]
 [2.6335595]]
[[0.4837762 ]
 [2.64001186]]
[[0.49088393]
 [2.64453702]]
[[0.49777834]
 [2.64764011]]
[[0.50451302]
 [2.64969394]]
[[0.51112748]
 [2.65097369]]
[[0.51765093]
 [2.65168243]]
[[0.5241049 ]
 [2.65197007]]
[[0.5305053 ]
 [2.65194724]]
[[0.53686387]
 [2.65169559]]
[[0.54318927]
 [2.65127538]]
[[0.54948791]
 [2.65073109]]
[[0.55576452]
 [2.65009555]]
[[0.56202258]
 [2.649393  ]]
[[0.56826469]
 [2.6486413 ]]
[[0.57449275]
 [2.64785366]]
[[0.58070816]
 [2.64703982]]
[[0.58691198]
 [2.64620697]]
[[0.59310498]
 [2.64536041]]
[[0.59928773]
 [2.64450405]]
[[0

In [16]:
x = np.array([1,15])
x.T @ w_updated

array([36.49439752])