In [84]:
import numpy as np

In [85]:
x=np.array([[1,1,1,1,1,1,1,1,1,1], [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]])  # Here I am taking Extra column having value 1 because we can use direct formula
y = np.array([2.3, 4.1, 5.8, 8.0, 10.2, 11.8, 14.1, 15.7, 18.2, 20.5])

In [86]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [87]:
w_updated,w_ini = np.zeros((2,1)) , np.zeros((2,1))

for i in range(1000):
    print(w_ini)
    w_updated = w_ini - (0.0001 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated
    


[[0.]
 [0.]]
[[0.00738   ]
 [0.05165333]]
[[0.01456568]
 [0.10195384]]
[[0.02156214]
 [0.15093695]]
[[0.02837433]
 [0.19863717]]
[[0.03500708]
 [0.24508811]]
[[0.04146509]
 [0.29032249]]
[[0.04775293]
 [0.33437218]]
[[0.05387506]
 [0.3772682 ]]
[[0.05983583]
 [0.41904077]]
[[0.06563945]
 [0.45971933]]
[[0.07129006]
 [0.49933252]]
[[0.07679164]
 [0.53790825]]
[[0.08214812]
 [0.57547371]]
[[0.08736328]
 [0.61205534]]
[[0.09244084]
 [0.64767892]]
[[0.09738439]
 [0.68236954]]
[[0.10219744]
 [0.71615165]]
[[0.10688342]
 [0.74904903]]
[[0.11144565]
 [0.78108487]]
[[0.11588738]
 [0.81228172]]
[[0.12021175]
 [0.84266157]]
[[0.12442185]
 [0.87224581]]
[[0.12852067]
 [0.90105529]]
[[0.13251112]
 [0.9291103 ]]
[[0.13639604]
 [0.95643059]]
[[0.1401782 ]
 [0.98303542]]
[[0.14386029]
 [1.00894352]]
[[0.14744492]
 [1.03417315]]
[[0.15093465]
 [1.05874208]]
[[0.15433198]
 [1.0826676 ]]
[[0.15763931]
 [1.10596659]]
[[0.160859  ]
 [1.12865543]]
[[0.16399336]
 [1.15075013]]
[[0.16704461]
 [1.17226623]]
[

In [88]:
x = np.array([1,15])
x.T @ w_updated

array([29.90178798])