In [1]:
import numpy as np

In [2]:
x=np.array([[1,1,1,1,1,1,1,1,1,1], [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]])  # Here I am taking Extra column having value 1 because we can use direct formula
y = np.array([7.3, 9.1, 10.8, 13.0, 15.2, 16.8, 19.1, 20.7, 23.2, 25.5])

In [3]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [4]:
w_updated,w_ini = np.zeros((2,1)) , np.zeros((2,1))

for i in range(1000):
    print(w_ini)
    w_updated = w_ini - (0.0001 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated
    


[[0.]
 [0.]]
[[0.01071333]
 [0.06998667]]
[[0.02116291]
 [0.13813773]]
[[0.03135563]
 [0.20450126]]
[[0.04129822]
 [0.26912409]]
[[0.05099723]
 [0.33205181]]
[[0.06045904]
 [0.39332883]]
[[0.06968986]
 [0.45299837]]
[[0.07869574]
 [0.51110255]]
[[0.08748257]
 [0.56768237]]
[[0.09605608]
 [0.62277775]]
[[0.10442186]
 [0.67642758]]
[[0.11258534]
 [0.72866973]]
[[0.12055183]
 [0.77954106]]
[[0.12832648]
 [0.82907748]]
[[0.13591431]
 [0.87731396]]
[[0.14332022]
 [0.92428455]]
[[0.15054896]
 [0.97002241]]
[[0.15760518]
 [1.01455982]]
[[0.16449339]
 [1.05792823]]
[[0.17121799]
 [1.10015826]]
[[0.17778326]
 [1.14127974]]
[[0.18419338]
 [1.18132168]]
[[0.19045241]
 [1.22031238]]
[[0.19656429]
 [1.25827937]]
[[0.20253289]
 [1.29524947]]
[[0.20836196]
 [1.33124878]]
[[0.21405514]
 [1.36630273]]
[[0.21961599]
 [1.40043609]]
[[0.22504798]
 [1.43367297]]
[[0.23035448]
 [1.46603686]]
[[0.23553877]
 [1.49755061]]
[[0.24060406]
 [1.52823651]]
[[0.24555346]
 [1.55811622]]
[[0.25039   ]
 [1.58721087]]
[

In [5]:
x = np.array([1,15])
x.T @ w_updated

array([39.81919787])