<h2> With Library 

In [13]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
import numpy as np

In [14]:
x = np.array([[1,10],[3,14],[4,15],[6,18],[7,20]])
y=np.array([9,10,13,14,16])

In [15]:
model= LinearRegression()

In [16]:
model.fit(x,y)

LinearRegression()

In [ ]:
# This gives b1,b2,b3,.....

In [17]:
(model.coef_) 

array([ 2.96078431, -1.11764706])

In [ ]:
# This givs b0

In [18]:
model.intercept_

np.float64(17.176470588235308)

In [21]:
new_x=[[2,12]]

In [22]:
predicted_value=model.predict(new_x)

In [23]:
predicted_value

array([9.68627451])

<h2> Without Library 

In [36]:
x = np.array([[1,1,10],[1,3,14],[1,4,15],[1,6,18],[1,7,20]])
y=np.array([9,10,13,14,16])

In [37]:
x_tranpose=x.T

In [38]:
x_tranpose

array([[ 1,  1,  1,  1,  1],
       [ 1,  3,  4,  6,  7],
       [10, 14, 15, 18, 20]])

<h2> parameters = (x^t.x)^-1 . x^t.y

In [39]:
xn=x_tranpose@x

In [40]:
xn2=np.dot(x_tranpose,x)

In [41]:
xn

array([[   5,   21,   77],
       [  21,  111,  360],
       [  77,  360, 1245]])

In [42]:
xn2

array([[   5,   21,   77],
       [  21,  111,  360],
       [  77,  360, 1245]])

In [43]:
xn_inverse=np.linalg.inv(xn)

In [44]:
xn_=np.dot(x_tranpose,y)

In [45]:
xn_final=xn_inverse@xn_

In [46]:
xn_final

array([17.17647059,  2.96078431, -1.11764706])

In [49]:
New_x=[[1,2,12]]

In [50]:
predicted_value=New_x@xn_final

In [51]:
predicted_value

array([9.68627451])